export const baseSizes = ['large', 'middle', 'small'] as const;

export const baseAlign = ['start', 'end', 'center', 'baseline'] as const;

export const baseDirection = ['vertical', 'horizontal'] as const;

export const supportIconList = [
  'icon-pause',
  'icon-code',
  'icon-menu',
  'icon-unorderedlist',
  'icon-drag',
  'icon-fire',
  'icon-thunderbolt',
  'icon-info-circle-fill',
  'icon-question-circle-fill',
  'icon-warning-circle-fill',
  'icon-folder-fill',
  'icon-folder-open-fill',
  'icon-eye-fill',
  'icon-Gitlab-fill',
  'icon-android-fill',
  'icon-apple-fill',
  'icon-windows-fill',
  'icon-QQ',
  'icon-weibo',
  'icon-wechat-fill',
  'icon-play-circle',
  'icon-earth',
  'icon-warning-circle',
  'icon-sync',
  'icon-reload',
  'icon-message',
  'icon-dashboard',
  'icon-poweroff',
  'icon-setting',
  'icon-eye',
  'icon-location',
  'icon-edit-square',
  'icon-export',
  'icon-import',
  'icon-appstore',
  'icon-adduser',
  'icon-addteam',
  'icon-linechart',
  'icon-barchart',
  'icon-redenvelope',
  'icon-home',
  'icon-filter',
  'icon-folder',
  'icon-folder-open',
  'icon-calendar',
  'icon-camera',
  'icon-cloud-download',
  'icon-sound',
  'icon-phone',
  'icon-tag',
  'icon-tags',
  'icon-shrink',
  'icon-arrawsalt',
  'icon-arrowright',
  'icon-arrowup',
  'icon-arrowleft',
  'icon-arrowdown',
  'icon-vertical-align-botto',
  'icon-totop',
  'icon-vertical-align-top',
  'icon-download',
  'icon-outdent',
];
